### PR TITLE
Cascading deletes feature

### PR DESCRIPTION
**Pull request by Evertt**
I think it's finished, but for some reason I can't get the tests to work. Could you maybe help me with that?

### CODE REVIEW

**Comment by RemiCollin** [comment]
Having a look

**Comment by RemiCollin** [comment]
You can't really rely on the count() method for testing as the database is only blandked at test initialisation. I would rather test on the related entity's id, using a simple find($id) method.

**Comment by Evertt** [comment]
Okay, that's one thing going wrong then. Another thing is that the CascadingDeletesPlugin never even runs. I found that out, because I put a `die('test');` in the plugin to see if the code would ever die, but it didn't. What am I doing wrong?

**Comment by RemiCollin** [comment]
Ok, I got it now. The test suite actually doesn't use the AnalogueServiceProvider, but initializes analogue as a standalone composer package. You need to register the CascadingDeletesPlugin in the init.php file : https://github.com/analogueorm/analogue/blob/5.1/tests/init.php

**Pull request closed without merging**
