### PR TITLE
New trait

### PR DESCRIPTION
**Pull request by Evertt**
I believe that in the last refactoring you did made it possible to create Entity classes that don't implement the Mappable interface, is that correct? I haven't tested it yet, but that's something I like.

Now this new trait I'm proposing allows entities that have private properties, yet public getter and setter methods for those properties, to make those properties seem like their public.

So let's say you have this Entity:

``` php
<?php namespace TodoModule\Model\Entities;

use Analogue\ORM\MagicallyAccessiblePropertiesTrait;

/**
* Todo
*/
class Todo
{
    use MagicallyAccessiblePropertiesTrait;

    /**
     * @var integer
     */
    private $id;

    /**
     * @var string
     */
    private $title;

    function __construct($title)
    {
        $this->title = $title;
    }

    /**
     * Gets the value of title.
     *
     * @return string
     */
    public function getTitle()
    {
        return $this->title;
    }

    /**
     * Sets the value of title.
     *
     * @param string $title the title
     *
     * @return self
     */
    public function setTitle($title)
    {
        $this->title = $title;

        return $this;
    }
}
```

Now since `Todo` uses the trait and the title has getters and setters, one can access the title as if it were public, like this:

``` php
$todo = new Todo('Wash the dishes');
echo $todo->title;
```

However, the `id` property is still protected, because it has no getters nor setters. In a template this syntax is just easier on the eyes than `$todo->getTitle();`. Now if a developer would wish to use their entity as if it were an array, that's also possible with this trait. The developer only has to make their entity implement `ArrayAccess` and then he can access the title of the todo by using `$todo['title']`.

What do you think?

### CODE REVIEW

**Comment by RemiCollin** [comment]
These POPO Entities are not fully tested right now, i'll merge this when they will be.

**Comment by Evertt** [comment]
Maybe we want to change the name of the trait though, since it's a bit long. :-)

**Comment by RemiCollin** [comment]
Something like 'MagicPropertiesTrait' will do I guess.

**Comment by Evertt** [comment]
You're not going to implement this anymore?

**Comment by RemiCollin** [comment]
Actually, It's currently a work in progress in `dev-master`, along with full support of POPO entities, and lots of new stuff, which I hope can document soon.

**Pull request closed without merging**
