### PR TITLE
Added a helper

### PR DESCRIPTION
**Pull request by Evertt**
I wanted to add more helpers like `repository()` and `map()`, but those functions are not (statically) available.

### CODE REVIEW

**Comment by RemiCollin** [comment]
Yes those helpers would be nice :) 

On the next coming patch there is a static method getInstance() which return the manager object, on the manager so it will make our life easier, so we can call :

```
Manager::getInstance()->mapper(...);
Manager::getInstance()->repository(...);
etc..
```

**Comment by Evertt** [comment]
Now you can say `store($entity)` instead of `mapper($entity)->store(entity)` which is a bit redundant.

**Comment by RemiCollin** [comment]
I think we should check for function existance (the same way laravel do it with their helpers), to avoid redeclaring a potentially existing function.

**Comment by Evertt** [comment]
Yes I agree. I didn't do it yet just out of laziness. :-$

**Comment by RemiCollin** [comment]
Added with function_exists() tests https://github.com/analogueorm/analogue/commit/c15cd365fe1eb20674ebacc246ee9ec525e6acc4

**Pull request closed without merging**
