### PR TITLE
[Feature] be able to watch value-objects for changes

### PR DESCRIPTION
**Pull request by Evertt**
So I have a `Person` with a value-object `Identity`, with attributes like `name` and `surname`. The person also has an attribute called `slug`, which is based on the `name` and `surname` of `Identity`. So in order to keep `slug` up to date, I need to be able to watch `Identity` for changes. Well that's what this pull-request is for. It makes the following code possible:

    class Person extends Entity
    {
        public function identityChanged($identity)
        {
            $this->attributes['slug'] = str_slug($identity->name . ' ' . $identity->surname);
        }
    }

### CODE REVIEW

**Comment by RemiCollin** [comment]
Simply use a mutator method for this, that's precisely what they are for :

```php
public function setIdentityAttribute($identity)
{
    $this->attributes['slug'] = str_slug($identity->name . ' ' . $identity->surname);
    $this->identity = $identity;
}
```

**Comment by Evertt** [comment]
Does that mean you'd have to create a new Identity object every time you want to change the name?
Like this?

```php
$newIdentity = new Identity('John', 'Doe');
$person->identity = $newIdentity;
```

Okay it's not terrible I admit, but still. ;-)

**Comment by RemiCollin** [comment]
Yes, a Value Object should be immutable. Think of it as a custom variable type, nothing more. I'll probably get rid of the __set() method on a future version, i just keep it now for backward compatibility.

**Comment by Evertt** [comment]
Okay thank you. I’m happy I’m learning more about best practices in programming. :-)

**Comment by RemiCollin** [comment]
Thet's also why I'm working on a whole new documentation, all this concepts need to be better explained.

**Comment by Evertt** [comment]
Hey I wonder, if we'd set up a whole webpage on github.io for this project, with attractive looking docs etc, it might get much more popular than it is now. :-)

What do you think?

**Comment by RemiCollin** [comment]
The website design is already done in fact, i'll put it online as soon as the actual documentation is finished :)

**Pull request closed without merging**
