### PR TITLE
5.3 dev

### PR DESCRIPTION
**Pull request by tabennett**
I've taken a stab at implementing #101. This is probably going to need some cleanup, but I've tried to following the concepts that you laid out (namely, using higher level ResultBuilder that builds out an array of entities by calling each the appropriate ResultBuilder for each record). 
To implement table inheritance, all you have to do is define some meta values on the base mapper class. As example, we could define the following configuration on a base Vehicle mapper:
```php
/**
     * @var string
     */
    protected $inheritanceType = "single_table";

    /**
     * @var string
     */
    protected $discriminatorColumn = "type";

    /**
     * @var array
     */
    protected $discriminatorColumnMap = [
        "vehicle" => "App\Entities\Vehicle",
        "car"     => "App\Entities\Car",
        "truck"   => "App\Entities\Truck"
    ];
```

This follows the same inheritance mapping configuration as used by [Doctrine](http://docs.doctrine-project.org/projects/doctrine-orm/en/latest/reference/inheritance-mapping.html). I did this for the following reasons:

1. People that have used Doctrine before and are familiar with this configuration will be able to get up and running quicker.
2. This opens the door for us to implement class table inheritance later on (which would be very nice to have but is beyond the scope of this PR).

The only major issue I have with this is that I wasn't able to figure out how to get an instance of the `Manager` class without using Laravel's IOC container (which might not be the most ideal way to do that and feels a bit weird to be doing). Please let me know what you think.

### CODE REVIEW

**Comment by RemiCollin** [comment]
Looks good! To instantiate the manager you can simply call the static method `Manager::getInstance()`, as, you're right, we shouldn't rely on the Ioc container for it. 

Some thought about the `$discriminatorColumnMap`; I guess this could be optionnal, and use the actual class name as value of the `type` column (following the same pattern as polymorphic relations), what do you think ?

**Comment by tabennett** [comment]
I can push out an update that uses ```Manager::getInstance()```.
For the ```$discriminatorColumnMap```, the reason I put that in there was because

- I think it's a good idea that we provide a way to keep the value of the discriminator column as decoupled from the Entity object as possible, so that people can map any entity class name that they want to any possible discriminator column string value that they want.
- If people are namespacing their entities folder (I keep my entities in an *app/Entities* under the ```App\Entities``` namespace), I didn't want them to be forced to always store the entire fully qualified class name inside of that column (that would create a tight coupling between stored data and this ORM).

If I understand what you're saying, we could provide a *default* option if no ```$discriminatorColumnMap``` value is provided in the map where we try and use the value of the discriminator column as the classname? That way people who don't namespace their entities could just use `Car` or `Truck` as the string value of that column without having to define the mapping?

**Comment by RemiCollin** [comment]
Exactly, the idea is by default to assume that the discriminator column is the fully qualified class name if no $discriminatorMap is set. Tight coupling isn't so much a concern as far as we provide a way to fine tune it.

**Comment by tabennett** [comment]
Take a look at these latest commits and let me know what you think:
- The manager instance is now injected into the `ResultBuilder` class (for easier testing).
- Cleaned up some old variables in the `ResultBuilder`class that I'd accidentally left lying around.
- By default, if now discriminator map is set, it'll try and use the value of the discriminator column as the entity class name.

**Comment by RemiCollin** [comment]
Saw a typo in ResultBuilder:87 : $this->defaulMapper 

Otherwise, looks good to me. I'll take care of adding Tests as I'm working on the new test suite, so we'll see how it behaves :)

**Comment by tabennett** [comment]
Just pushed out a fix for that typo. I ran your test suite before I first PR'ed this but I was in a hurry yesterday afternoon and forgot to run them or I would have caught that bug. If you'd like, I can write a unit test for the behavior of the `ResultBuilder` class. Just let me where you'd want it at (inside the cases folder) ?

**Comment by tabennett** [comment]
Another question: should a parent mapper be able to save/persist an instance of a child entity class? For example, should we be able to say something like this:
```php
$car = new \App\Entities\Car;
// and then later on
$vehicleMapper->store($car);
```

If so, we'll need update the `Mapper::checkEntityType` method to handle this. Maybe something like this:
```php
if (get_class($entity) != $this->entityMap->getClass() && !is_subclass_of($entity, $this->entityMap->getClass())) {
            $expected = $this->entityMap->getClass();
            $actual = get_class($entity);
            throw new InvalidArgumentException("Expected : $expected, got $actual.");
        }
```

Or we could possibly use reflection to handle it.

**Comment by RemiCollin** [comment]
Of course tests are more than welcome! 

About your last question, I think we'd better handle this in the `Manager` class, which already have a store method. At this point it only accepts a single entity as argument, but we could make it accepts an array or collection, split them by `class`, then handle each subsets to the corresponding Mappers.

**Comment by tabennett** [comment]
I'm going to write up some tests for this. 

For the mapper issue, are you sure that handling this in the manager class would solve the issue? The issue I'm having is that right now is that I have code where I'm working with a collection of entities but there's no way for sure that I can know exactly what type of entity it is (in the STI inheritance chain) that I have. I'm trying to use the base `EntityMap` mapper to work with them, but it's breaking each time I try to store/delete because that call to `Mapper::checkEntityType` is only checking the exact string class name of the entity; not the type. This seems a bit wrong to me since technically, my two entity classes are all instances of the same type of class?

**Comment by RemiCollin** [comment]
Yes, we need to make some change to the `Manager` class to handle this though. But the idea is for the manager to dispatch each Entity from an array or collection of mixed entities to the correct Mapper.

**Comment by tabennett** [comment]
I thought the manager class already does this though? `Analogue\ORM\System\Manager` has a store method that proxies the call to the underlying mapper instance for the entity:
```php
public function store($entity)
{
    return $this->mapper($entity)->store($entity);
}
```

If I'm not mistaken, that basically finds the mapper for the given entity and if an instance of it doesn't already exist it creates it and stores it there on the Manager class right?

But that's not ever being called in my case. I'm calling `store()` directly on a mapper instance, not the manager class; the manager doesn't get called at all during that procedure (I use it to get my mapper instance but that's about it). So are you saying that we can only call store on the manager instance (and not a mapper instance) if we're using STI? I feel like maybe there's something I'm missing here or I'm just confused.

**Comment by tabennett** [comment]
Ok, I see what you're saying though; The manager `store()` method doesn't take a collection of entities. But still, I'm going to have to change/override methods on my repository class for my base entity so that it doesn't use the mapper and instead uses the manager?

**Comment by RemiCollin** [comment]
Well, idealy yes, as it would feels wrong for a Mapper which is dedicated to a given Entity to handle another type. I have to think about this as it would introduce a BC, but this would also make this STI implementation much more cleaner.

**Pull request merged**
